#!/usr/bin/python3
import sys


def factorise(number):
    # prog prints the product of a numb using two possible factors.
    for factor1 in range(0, number + 1, 1):
        if number % factor1 == 0:
            number / factor1 == factor2
    return factor1, factor2


filename = sys.argv[1]

with open(filename, 'r') as file:
    for line in file.readlines():
        number = int(line.rstrip())
        print("{}={}*{}".format(number, factor1, factor2))
